POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "nlw unite",
  "details": null,
  "maximumAttendees": 2
}

###

POST http://localhost:3333/events/0ce0abb8-7137-4350-beed-aead10545dc4/attendees
Content-Type: application/json

{
  "name": "Israel Oliveira",
  "email": "israel@hotmail.com"
}

###

GET http://localhost:3333/events/0ce0abb8-7137-4350-beed-aead10545dc4

###

GET http://localhost:3333/attendees/1/badge

###

GET http://localhost:3333/attendees/2/check-in

###

GET http://localhost:3333/events/0ce0abb8-7137-4350-beed-aead10545dc4/attendees

###

GET http://localhost:3333/events/0ce0abb8-7137-4350-beed-aead10545dc4/attendees?query=Evandro
